"""Add bank statements model

Revision ID: b9efb8aaeb37
Revises: 202603190008
Create Date: 2026-03-20 09:36:53.010942

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'b9efb8aaeb37'
down_revision = '202603190008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_email', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_statements_month'), 'bank_statements', ['month'], unique=False)
    op.create_index(op.f('ix_bank_statements_uploaded_at'), 'bank_statements', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_bank_statements_uploaded_by_email'), 'bank_statements', ['uploaded_by_email'], unique=False)
    op.create_index(op.f('ix_bank_statements_year'), 'bank_statements', ['year'], unique=False)
    op.create_foreign_key(None, 'ledger_entries', 'term_deposits', ['term_deposit_id'], ['id'])
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.drop_constraint(None, 'ledger_entries', type_='foreignkey')
    op.drop_index(op.f('ix_bank_statements_year'), table_name='bank_statements')
    op.drop_index(op.f('ix_bank_statements_uploaded_by_email'), table_name='bank_statements')
    op.drop_index(op.f('ix_bank_statements_uploaded_at'), table_name='bank_statements')
    op.drop_index(op.f('ix_bank_statements_month'), table_name='bank_statements')
    op.drop_table('bank_statements')
    # ### end Alembic commands ###
